function [gradebook_path, hw_name] = singleStudent()
    [~,gradebook_path] = uigetfile([sub_path '\*.csv'],'Select the .csv downloaded from canvas');
    f = figure('Name','Select Homework',...
               'Visible','on',...
               'Units','Normalized',...
               'Position',[.4 .3 .25 .4]);
    list = uicontrol(f,'Style','listbox',...
                       'String',{'Homework 01 - Basics',...
                                 'Homework 02 - Functions',...
                                 'Homework 03 - Vectors and Strings',...
                                 'Homework 04 - Logicals and Masking',...
                                 'Homework 05 - Arrays and Images',...
                                 'Homework 06 - Conditionals',...
                                 'Homework 07 - Iteration',...
                                 'Homework 08 - Low Level IO',...
                                 'Homework 09 - High Level IO',...
                                 'Homework 10 - Structures',...
                                 'Homework 11 - Plotting and Numerical Methods',...
                                 'Homework 12 - Recursion'},...
                       'Units','Normalized',...
                       'Position',[.05 .35 .90 .60]);
    chkbx = uicontrol(f,'Style','checkbox',...
                        'String','Resubmission',...
                        'Units','Normalized',...
                        'Position',[.1 .25 .8,.1]);
    uicontrol(f,'Style','pushbutton',...
                'String','Submit to grader',...
                'Units','Normalized',...
                'Position',[.25 .05 .5,.15],...
                'Callback','uiresume(gcbf)');
    uiwait(f);
    hw_name = list.String{list.Value};
    resub = logical(chkbx.Value);
    close(f)
    if resub
        hw_name = [hw_name(1:find(hw_name == '-')+1) 'Resubmission'];
    end
end